version: '3.8'
services:
  api:
    build: .
    container_name: fastapi
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Bababubu17
      - DATABASE_NAME=Socialmedia
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=1b0b01deb22e015c2e69937713016261699ae7c5fd9fe63ae5deaf9f59ea6e97
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  db:
    image: postgres
    container_name: postgres-db1
    environment:
    - POSTGRES_PASSWORD=Bababubu17
    - POSTGRES_DB=Socialmedia
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
